apiVersion: v1
kind: Pod
metadata:
  name: mypod2
  labels:
    app: webserver

spec:
  containers:
  - name: mycontainer
    image: nginx:latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
